services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/RAID/torrents/config:/config
      - /mnt/RAID/torrents/download:/downloads
      - /mnt/RAID/torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
